sudo: required
service:
 - docker

before_install:
 - docker build -t verajack/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true verajack/docker-react npm run test -- -- coverage

deploy:
  provider: elasticbeanstalk
  region: 
